# Generated by Django 3.1.5 on 2021-02-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('cartype', models.CharField(db_column='carType', max_length=45, primary_key=True, serialize=False)),
                ('chgertype', models.IntegerField(blank=True, db_column='chgerType', null=True)),
            ],
            options={
                'db_table': 'car_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvCodeInf',
            fields=[
                ('codeid', models.CharField(db_column='codeId', max_length=5, primary_key=True, serialize=False)),
                ('codename', models.CharField(blank=True, db_column='codeName', max_length=100, null=True)),
                ('codetype', models.CharField(blank=True, db_column='codeType', max_length=10, null=True)),
                ('useyn', models.CharField(blank=True, db_column='useYN', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ev_code_inf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvInfo',
            fields=[
                ('evsn', models.BigAutoField(db_column='evSn', primary_key=True, serialize=False)),
                ('statid', models.CharField(blank=True, db_column='statId', max_length=8, null=True)),
                ('statnm', models.CharField(blank=True, db_column='statNm', max_length=100, null=True)),
                ('chgerid', models.CharField(blank=True, db_column='chgerId', max_length=2, null=True)),
                ('chgertype', models.CharField(blank=True, db_column='chgerType', max_length=2, null=True)),
                ('addr', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('usetime', models.CharField(blank=True, db_column='useTime', max_length=50, null=True)),
                ('busiid', models.CharField(blank=True, db_column='busiId', max_length=2, null=True)),
                ('businm', models.CharField(blank=True, db_column='busiNm', max_length=50, null=True)),
                ('busicall', models.CharField(blank=True, db_column='busiCall', max_length=20, null=True)),
                ('stat', models.CharField(blank=True, max_length=1, null=True)),
                ('statupddt', models.DateTimeField(blank=True, db_column='statUpdDt', null=True)),
                ('powertype', models.CharField(blank=True, db_column='powerType', max_length=20, null=True)),
                ('zcode', models.CharField(blank=True, max_length=2, null=True)),
                ('parkingfree', models.CharField(blank=True, db_column='parkingFree', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ev_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvReview',
            fields=[
                ('reviewsn', models.IntegerField(db_column='reviewSn', primary_key=True, serialize=False)),
                ('evsn', models.IntegerField(blank=True, db_column='evSn', null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ev_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvStation',
            fields=[
                ('evsn', models.BigAutoField(db_column='evSn', primary_key=True, serialize=False)),
                ('statid', models.CharField(blank=True, db_column='statId', max_length=8, null=True)),
                ('statnm', models.CharField(blank=True, db_column='statNm', max_length=100, null=True)),
                ('addr', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('usetime', models.CharField(blank=True, db_column='useTime', max_length=50, null=True)),
                ('busiid', models.CharField(blank=True, db_column='busiId', max_length=2, null=True)),
                ('businm', models.CharField(blank=True, db_column='busiNm', max_length=50, null=True)),
                ('busicall', models.CharField(blank=True, db_column='busiCall', max_length=20, null=True)),
                ('statupddt', models.DateTimeField(blank=True, db_column='statUpdDt', null=True)),
                ('powertype', models.CharField(blank=True, db_column='powerType', max_length=4, null=True)),
                ('zcode', models.CharField(blank=True, max_length=2, null=True)),
                ('parkingfree', models.CharField(blank=True, db_column='parkingFree', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ev_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvStationChgertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evsn', models.BigIntegerField(db_column='evSn')),
                ('statid', models.CharField(db_column='statId', max_length=8)),
                ('chgerid', models.CharField(db_column='chgerId', max_length=2)),
                ('chgertype', models.CharField(db_column='chgerType', max_length=5)),
            ],
            options={
                'db_table': 'ev_station_chgertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvStationInoutStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initdate', models.DateField(blank=True, db_column='initDate', null=True)),
                ('evsn', models.BigIntegerField(blank=True, db_column='evSn', null=True)),
                ('statnm', models.CharField(blank=True, db_column='statNm', max_length=100, null=True)),
                ('visitcnt', models.BigIntegerField(blank=True, db_column='visitCnt', null=True)),
                ('chgeravgtime', models.IntegerField(blank=True, db_column='chgerAvgTime', null=True)),
            ],
            options={
                'db_table': 'ev_station_inout_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvStationStatus',
            fields=[
                ('evsn', models.BigIntegerField(db_column='evSn', primary_key=True, serialize=False)),
                ('statid', models.CharField(db_column='statId', max_length=8)),
                ('chgerid', models.CharField(db_column='chgerId', max_length=2)),
                ('stat', models.CharField(max_length=5)),
                ('upddt', models.DateTimeField(blank=True, db_column='updDt', null=True)),
            ],
            options={
                'db_table': 'ev_station_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvStationStatusStat',
            fields=[
                ('initdate', models.DateTimeField(db_column='initDate', primary_key=True, serialize=False)),
                ('evsn', models.BigIntegerField(db_column='evSn')),
                ('statid', models.CharField(db_column='statId', max_length=8)),
                ('chgerid', models.CharField(db_column='chgerId', max_length=2)),
                ('stat', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'ev_station_status_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyEvList',
            fields=[
                ('evsn', models.BigIntegerField(db_column='evSn', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='userId', max_length=45)),
            ],
            options={
                'db_table': 'my_ev_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionCode',
            fields=[
                ('zcode', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('carnum', models.CharField(db_column='carNum', max_length=45, primary_key=True, serialize=False)),
                ('cartype', models.CharField(blank=True, db_column='carType', max_length=45, null=True)),
                ('userid', models.CharField(blank=True, db_column='userId', max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.CharField(db_column='userId', max_length=45, primary_key=True, serialize=False)),
                ('nicknm', models.CharField(blank=True, db_column='nickNm', max_length=45, null=True)),
                ('usernm', models.CharField(blank=True, db_column='userNm', max_length=45, null=True)),
                ('pwd', models.CharField(blank=True, max_length=45, null=True)),
                ('phonenum', models.CharField(blank=True, db_column='phoneNum', max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
