# Generated by Django 3.1.5 on 2021-02-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evstationstatus',
            options={'managed': False},
        ),
    ]
