# Generated by Django 3.1.5 on 2021-02-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontApp', '0002_auto_20210215_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evstationchgertype',
            options={'managed': False},
        ),
    ]
