# Generated by Django 3.1.5 on 2021-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontApp', '0003_auto_20210215_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvRealTime',
            fields=[
                ('evsn', models.BigIntegerField(db_column='evSn', primary_key=True, serialize=False)),
                ('congestion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ev_real_time',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CarList',
        ),
        migrations.DeleteModel(
            name='EvStationInoutStat',
        ),
        migrations.DeleteModel(
            name='EvStationStatusStat',
        ),
    ]
