# Generated by Django 3.1.5 on 2021-02-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontApp', '0004_auto_20210216_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
    ]
